export const S = {
  header: {
    background: "#fff",
    padding: "14px 16px",
    borderBottom: "1px solid #E7E5E4",
    position: "sticky",
    top: 0,
    zIndex: 50,
  },
  body: {
    padding: "12px 16px 100px",
  },
  badge: {
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 700,
    border: "none",
    cursor: "pointer",
  },
  tag: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 6,
    fontSize: 11,
    background: "#E7E5E4",
    color: "#57534E",
  },
  backBtn: {
    background: "none",
    border: "none",
    fontSize: 22,
    color: "#78716C",
    cursor: "pointer",
    padding: "4px 8px 4px 0",
  },
  btnPrimary: (bg) => ({
    background: bg || "#2563EB",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "12px 20px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  }),
  btnSecondary: {
    background: "#fff",
    border: "1px solid #D6D3D1",
    color: "#57534E",
    borderRadius: 10,
    padding: "12px 20px",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,.85)",
    zIndex: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  card: (borderColor) => ({
    background: "#FAFAF9",
    border: "1px solid #E7E5E4",
    borderLeft: `5px solid ${borderColor}`,
    borderRadius: 10,
    padding: "12px 14px",
    marginBottom: 8,
    cursor: "pointer",
  }),
  itemRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginBottom: 2,
  },
  itemText: (color) => ({
    flex: 1,
    padding: "5px 10px",
    background: "#fff",
    border: "1px solid #E7E5E4",
    borderRadius: 6,
    borderLeft: `3px solid ${color}44`,
    fontSize: 13,
    color: "#292524",
    cursor: "text",
    WebkitTapHighlightColor: "transparent",
  }),
  itemInput: (color) => ({
    flex: 1,
    padding: "5px 10px",
    background: "#fff",
    border: `2px solid ${color}`,
    borderRadius: 6,
    fontSize: 13,
    color: "#1C1917",
    outline: "none",
    boxSizing: "border-box",
  }),
  editBtn: {
    background: "none",
    border: "none",
    color: "#78716C",
    cursor: "pointer",
    fontSize: 14,
    padding: 4,
    lineHeight: 1,
  },
  deleteBtn: {
    background: "none",
    border: "none",
    color: "#EF444488",
    cursor: "pointer",
    fontSize: 18,
    padding: 4,
    lineHeight: 1,
  },
  catLabel: (color) => ({
    fontSize: 10,
    fontWeight: 700,
    color: color,
    letterSpacing: 1,
    textTransform: "uppercase",
    margin: "8px 0 4px",
  }),
  shell: {
    fontFamily: "'DM Sans', -apple-system, system-ui, sans-serif",
    background: "#F5F5F4",
    color: "#1C1917",
    minHeight: "100vh",
    maxWidth: 430,
    margin: "0 auto",
    position: "relative",
  },
  nav: {
    display: "flex",
    background: "#fff",
    borderTop: "1px solid #E7E5E4",
    position: "fixed",
    bottom: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "100%",
    maxWidth: 430,
    zIndex: 100,
  },
  navBtn: (active) => ({
    flex: 1,
    padding: "10px 4px 14px",
    background: "none",
    border: "none",
    color: active ? "#2563EB" : "#A8A29E",
    fontSize: 10,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    borderTop: active ? "2px solid #2563EB" : "2px solid transparent",
  }),
};
